// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://labbmateggsxtqxybnaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhYmJtYXRlZ2dzeHRxeHlibmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NjE0NDcsImV4cCI6MjA2NDIzNzQ0N30.i-JP8AbKyu8IejrAn1bRB6e1_XHnqC_6rZYYmJ7DTfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);